get:
  summary: Gets an exam for class admin
  tags:
    - "Exam"
  security:
    - bearerAuth: []
  parameters:
    - in: path
      name: classId
      required: true
      schema:
        type: string
    - in: path
      name: examId
      required: true
      schema:
        type: string
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: '../../../swagger.config.yaml#/components/schemas/Exam'